/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import Logica.Jugador;
import Logica.Tablerologica;
import com.sun.javafx.scene.control.skin.TableColumnHeader;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;  
import javax.swing.table.TableColumnModel;

/**
 *
 * @author LENOVO
 */
public final class tablero extends javax.swing.JFrame {
    int turn=1;
    Jugador jugador11;
    Jugador jugador22;
    Jugador Jugador;
    Tablerologica tablero;
    int[][] matriz;
    DefaultTableModel model;
    int fila=6;
    int columna=7;
    int cont1=5,cont2=5,cont3=5,cont4=5,cont5=5,cont6=5,cont7=5;
    
    
   
   
    
    public tablero() {
         
        initComponents();
      
       TableColumn col;
        col=Tabla.getColumnModel().getColumn(3);
        col.setPreferredWidth(90);
        col.setMaxWidth(90);
        col.setMinWidth(90);
        Tabla.setRowHeight(25);
     
       
       
       
     
       matriz= new int[columna][fila];
       tablero = new Tablerologica();
       
       tablero.inicializarjuego(matriz);
       matriz=tablero.getMatriz();
       
       llenartabla(matriz, fila , columna);
       btnponer.setEnabled(false);
       
      
      
    }
   
    
    public void llenartabla (int [][] matriz, int fila, int columna){
       
       model = (DefaultTableModel) Tabla.getModel();
       
       
       
       model.setRowCount(fila);
       model.setColumnCount(columna);
       
       
       
       for(int i=0; i<columna; i++){
           for (int j=0; j<fila; j++){
               Tabla.setValueAt(matriz[i][j], j, i);
               
           }
       }
       
     
    
    
    }
    

    public void setTurno(int turno) {
        this.turn = turno;
    }
    
   

   

    public void setJugador1(Jugador jugador1) {
        this.jugador11 = jugador1;
    }

    public void setJugador2(Jugador jugador2) {
        this.jugador22 = jugador2;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel43 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        btnponer = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Turno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnempieza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel43.setText("CONECTA 4");

        btnponer.setText("Poner Ficha");
        btnponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnponerActionPerformed(evt);
            }
        });

        jLabel44.setText("Columna en la que desea tirar :");

        dato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoActionPerformed(evt);
            }
        });

        jLabel1.setText("TURNO DE");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "col1", "col2", "col3", "col4", "col5", "col6", "col7"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnempieza.setText("Quien Empieza");
        btnempieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempiezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(28, 28, 28)
                        .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnponer)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31))
                            .addComponent(btnempieza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Turno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)))
                .addComponent(jugador2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnempieza)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnponer))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnponerActionPerformed
             
      String ponerFicha= dato.getText();
      
      int numero=0;
      numero= Integer.parseInt(ponerFicha);
      try{
      if(numero==1){    
          cont1 = tablero.validarfila(numero-1,cont1);
          matriz[numero-1][cont1]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
          
      }else if (numero==2){ 
          
          cont2 = tablero.validarfila(numero-1,cont2);
          matriz[numero-1][cont2]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }else if (numero==3){ 
          
          cont3 = tablero.validarfila(numero-1,cont3);
          matriz[numero-1][cont3]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }else if (numero==4){ 
          
          cont4 = tablero.validarfila(numero-1,cont4);
          matriz[numero-1][cont4]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }else if (numero==5){ 
          
          cont5 = tablero.validarfila(numero-1,cont5);
          matriz[numero-1][cont5]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }else if (numero==6){ 
          
          cont6 = tablero.validarfila(numero-1,cont6);
          matriz[numero-1][cont6]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }else if (numero==7){ 
          
          cont7 = tablero.validarfila(numero-1,cont7);
          matriz[numero-1][cont7]=Jugador.getNumero();
          tablero.setMatriz(matriz);
          llenartabla(matriz, fila, columna);
          tablero.validarjugada(Jugador.getNumero());
          if(turn==1){setTurno(2);}else{setTurno(1);};
          Turnojugador(turn);
          Jugador =  Turnojugador(turn);
          Turno.setText(Turnojugador(turn).getNombre());
       }    
      
      }
      catch(Exception E){
      
          JOptionPane.showMessageDialog(null, "La columna " + numero + " ya esta llena");  
    }//GEN-LAST:event_btnponerActionPerformed
    }
      
    private void datoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datoActionPerformed

    private void btnempiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempiezaActionPerformed
     
         this.turn=(int)(Math.random()*2)+1; 
     Jugador =  Turnojugador(turn);
      Turno.setText(Jugador.getNombre());
      
      
      btnempieza.setEnabled(false);
      btnponer.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnempiezaActionPerformed

  public  Jugador Turnojugador(int num){
     
        if (num==1){
         
         return jugador11;
     }else{
         
        return jugador22; 
     }
      
  }
  
  public void validarjuego(){
      
     
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new tablero().setVisible(true);
                
                
              
            }
        });
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Turno;
    private javax.swing.JButton btnempieza;
    private javax.swing.JButton btnponer;
    private javax.swing.JTextField dato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jugador2;
    // End of variables declaration//GEN-END:variables
}
